<a href="https://colab.research.google.com/github/JISHANA-T/Cohrot-workout-result/blob/main/Data_Types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
jish=np.array([1,2,3,4,5])

In [ ]:
print(jish)

[1 2 3 4 5]


In [ ]:
import  pandas as pd


In [ ]:
print(jish+5)

[ 6  7  8  9 10]


In [ ]:
print(jish*5)

[ 5 10 15 20 25]


In [ ]:
print(jish**5)

[   1   32  243 1024 3125]


In [ ]:
add=np.mean(jish)
print(add)

3.0


In [ ]:
jash=np.mean(jish)
print(jash)


3.0


In [ ]:
add=np.sum(jish)
print(add)

15


In [ ]:
import numpy as np
a=pd.dataframe({'Rank':[1,2,3,4,5], 'Name':['Asna','Jishana','Anitta','Ardra','Safa']})
a('c')==a['Rank']+a['Name']
9print(a)

AttributeError: module 'pandas' has no attribute 'dataframe'

In [ ]:
import pandas as pd
from google.colab import files
upload=files.upload()

Saving money.csv to money.csv


In [ ]:
import pandas as pd
file1=list(upload.keys())[0]
file1=pd.read_csv(file1)
print(file1['M1'])



0      110.20
1      111.75
2      112.95
3      113.93
4      115.08
        ...  
131    475.70
132    490.90
133    505.20
134    517.20
135    523.40
Name: M1, Length: 136, dtype: float64


In [ ]:
x=file1['M1']
print(x)
y=file1['Y']
print(y)

0      110.20
1      111.75
2      112.95
3      113.93
4      115.08
        ...  
131    475.70
132    490.90
133    505.20
134    517.20
135    523.40
Name: M1, Length: 136, dtype: float64
0       267.6
1       277.1
2       294.8
3       306.3
4       320.4
        ...  
131    3109.6
132    3173.8
133    3267.0
134    3346.6
135    3431.7
Name: Y, Length: 136, dtype: float64


In [ ]:
import statsmodels.api as asna
x=asna.add_constant(x)
model=asna.OLS(y,x).fit()
print(model.summary())

print(file1.describe())

                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.995
Method:                 Least Squares   F-statistic:                 2.752e+04
Date:                Fri, 21 Mar 2025   Prob (F-statistic):          5.65e-157
Time:                        05:17:19   Log-Likelihood:                -751.25
No. Observations:                 136   AIC:                             1507.
Df Residuals:                     134   BIC:                             1512.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -646.4482     11.940    -54.141      0.0



---

